title: ddot.it - Connect anything with everything.
description: "A minimal plain-text syntax for building a knowledge graph across any tool or document."
theme: just-the-docs

url: https://ddot.it

favicon_ico: "/assets/images/favicon.svg"
# logo: "/images/icon-128.png"

aux_links:
  GitHub: https://github.com/Calpano/ddot.it
aux_links_new_tab: true

heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

plugins:
  - jekyll-readme-index
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "README.md"
    values:
      nav_exclude: true
